import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../../components/PageTitle";
import RelatedBlogs from "../../components/RelatedBlogs";
import { FeaturedBlogType } from "../../Types/types";

interface Props {
  featuredBlog: FeaturedBlogType,
  featuredBlogs: FeaturedBlogType[],
  relatedBlogs: FeaturedBlogType[],
}

const BlogDetail: NextPage<Props> = ({ featuredBlog, featuredBlogs, relatedBlogs }) => {
  return (
    <>
      <Head>
        <title>Store - title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={featuredBlog.title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={featuredBlog.img} alt={featuredBlog.title} />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">{featuredBlog.category}</span>

                    <span>
                      <span className="cl4">By </span> {featuredBlog.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>date</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{featuredBlog.title}</h4>

                  <p className="stext-117 cl6 p-b-26">{featuredBlog.first_content}</p>

                  <p className="stext-117 cl6 p-b-26">{featuredBlog.second_content}</p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs relatedBlogs={relatedBlogs} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default BlogDetail;

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch("http://localhost:5001/blogs")
  const featuredBlogs: FeaturedBlogType[] = await res.json();

  const paths = featuredBlogs.map((featuredBlog) => {
    return {
      params: {
        id: featuredBlog.id
      }
    }
  });

  return {
    paths: paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (params?.id) {
    const res = await fetch(`http://localhost:5001/blogs/${params.id}`);
    const featuredBlog: FeaturedBlogType = await res.json();

    const resOfAllBlogs = await fetch(`http://localhost:5001/blogs`);
    const allBlogs: FeaturedBlogType[] = await resOfAllBlogs.json()

    const randomNumber = Math.floor(Math.random() * (allBlogs.length - 3));

    const resRelatedBlogs = await fetch(`http://localhost:5001/blogs?_start=${randomNumber}&_limit=3`);
    const relatedBlogs: FeaturedBlogType[] = await resRelatedBlogs.json()

    if (!res.ok) {
      return {
        notFound: true,
      }
    }

    return {
      props: {
        featuredBlog,
        relatedBlogs,
      },
    };
  }

  return {
    props: {
      notFound: true,
    },
  };


}