import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { BannerType, FeaturedBlogType, FeaturedProductType } from "../Types/types";

interface Props {
  banner: BannerType,
  featuredProducts: FeaturedProductType[],
  featuredBlogs: FeaturedBlogType[],
}

const Home: NextPage<Props> = ({ banner, featuredProducts, featuredBlogs }) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner {...banner} />

      <CategoryPicker />

      <FeaturedProducts featuredProducts={featuredProducts} />

      <FeaturedBlogs featuredBlogs={featuredBlogs} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {

  const resBanner = await fetch("http://localhost:5001/banner_content");
  const banner: BannerType = await resBanner.json()

  const resFeaturedProducts = await fetch("http://localhost:5001/products/?_limit=4");
  const featuredProducts: FeaturedProductType[] = await resFeaturedProducts.json()

  const resFeaturedBlogs = await fetch("http://localhost:5001/blogs/?_limit=3");
  const featuredBlogs: FeaturedBlogType[] = await resFeaturedBlogs.json()

  return {
    props: { banner, featuredProducts, featuredBlogs }
  }
}

